# Generated by Django 5.1.6 on 2025-09-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('Description', models.TextField(max_length=50)),
                ('Image', models.ImageField(max_length=255, upload_to='media/')),
                ('Adress', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=50)),
                ('Status', models.CharField(max_length=5)),
            ],
        ),
    ]
