# Generated by Django 5.1.6 on 2025-09-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Status',
        ),
        migrations.AddField(
            model_name='hotel',
            name='StatusType',
            field=models.CharField(choices=[('LIVE', 'Live'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Image',
            field=models.ImageField(max_length=255, upload_to='main/static/media'),
        ),
    ]
