# Generated by Django 5.1.6 on 2025-09-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_hotel_status_hotel_statustype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
