# Generated by Django 5.1.6 on 2025-09-20 12:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=15, region=None),
        ),
    ]
