# Generated by Django 5.1.6 on 2025-09-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_post_mobile_remove_post_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
    ]
