# Generated by Django 5.1.6 on 2025-09-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_post_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='accommodations',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blog',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
