# Generated by Django 5.1.6 on 2025-09-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_blog_adress_remove_blog_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='posts')),
                ('accommodations', models.PositiveIntegerField(default=1)),
                ('statustype', models.CharField(choices=[('LIVE', 'Live'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
