# Generated by Django 5.1.6 on 2025-09-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_destination_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='city',
        ),
    ]
